DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Tuoteryhma CASCADE;
DROP TABLE IF EXISTS Tuote CASCADE;
DROP TABLE IF EXISTS Tilaus CASCADE;
DROP TABLE IF EXISTS TuoteJaRyhmaYhdiste CASCADE;